[package]
name = "penumbra-stake"
version = "0.1.0"
authors = ["Penumbra Labs <team@penumbra.zone>"]
edition = "2021"
description = "The staking and delegation implementation for Penumbra"
repository = "https://github.com/penumbra-zone/penumbra/"
homepage = "https://penumbra.zone"
license = "MIT OR Apache-2.0"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Workspace dependencies
penumbra-crypto = { path = "../crypto" }
penumbra-proto = { path = "../proto" }

# Penumbra dependencies
tendermint = { git = "https://github.com/penumbra-zone/tendermint-rs.git", branch = "master" }
# External dependencies
anyhow = "1"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
bech32 = "0.8"
regex = "1.5"
once_cell = "1.8"

[dev-dependencies]
ed25519-consensus = "1.2"
rand_core = "0.6"

[build-dependencies]
vergen = "5"
